"""create access logs table

Revision ID: 6f58c71e6c7a
Revises: b2ba5f105d71
Create Date: 2026-09-02 17:32:27.491539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f58c71e6c7a'
down_revision: Union[str, Sequence[str], None] = 'b2ba5f105d71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('consent_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('purpose', sa.String(length=255), nullable=True),
    sa.Column('decision', sa.String(length=50), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('accessed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['consent_id'], ['consents.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_logs_accessed_at'), 'access_logs', ['accessed_at'], unique=False)
    op.create_index(op.f('ix_access_logs_consent_id'), 'access_logs', ['consent_id'], unique=False)
    op.create_index(op.f('ix_access_logs_document_id'), 'access_logs', ['document_id'], unique=False)
    op.create_index(op.f('ix_access_logs_hospital_id'), 'access_logs', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_access_logs_id'), 'access_logs', ['id'], unique=False)
    op.create_index(op.f('ix_access_logs_patient_id'), 'access_logs', ['patient_id'], unique=False)
    op.create_index(op.f('ix_access_logs_user_id'), 'access_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_access_logs_user_id'), table_name='access_logs')
    op.drop_index(op.f('ix_access_logs_patient_id'), table_name='access_logs')
    op.drop_index(op.f('ix_access_logs_id'), table_name='access_logs')
    op.drop_index(op.f('ix_access_logs_hospital_id'), table_name='access_logs')
    op.drop_index(op.f('ix_access_logs_document_id'), table_name='access_logs')
    op.drop_index(op.f('ix_access_logs_consent_id'), table_name='access_logs')
    op.drop_index(op.f('ix_access_logs_accessed_at'), table_name='access_logs')
    op.drop_table('access_logs')
    # ### end Alembic commands ###
