"""create consents table

Revision ID: b2ba5f105d71
Revises: d4cf6ec0b639
Create Date: 2026-09-02 14:14:22.809771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2ba5f105d71'
down_revision: Union[str, Sequence[str], None] = 'd4cf6ec0b639'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('requesting_hospital_id', sa.Integer(), nullable=False),
    sa.Column('requesting_user_id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('expiry_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requesting_hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['requesting_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consents_document_id'), 'consents', ['document_id'], unique=False)
    op.create_index(op.f('ix_consents_id'), 'consents', ['id'], unique=False)
    op.create_index(op.f('ix_consents_patient_id'), 'consents', ['patient_id'], unique=False)
    op.create_index(op.f('ix_consents_requesting_hospital_id'), 'consents', ['requesting_hospital_id'], unique=False)
    op.create_index(op.f('ix_consents_requesting_user_id'), 'consents', ['requesting_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consents_requesting_user_id'), table_name='consents')
    op.drop_index(op.f('ix_consents_requesting_hospital_id'), table_name='consents')
    op.drop_index(op.f('ix_consents_patient_id'), table_name='consents')
    op.drop_index(op.f('ix_consents_id'), table_name='consents')
    op.drop_index(op.f('ix_consents_document_id'), table_name='consents')
    op.drop_table('consents')
    # ### end Alembic commands ###
